name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: j178/prek-action@v1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up UV
      uses: astral-sh/setup-uv@v7
    - name: Cache pip
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}
    - name: Install UV and sync dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv==0.10.7
        uv sync --group dev
    - name: Run tests
      run: uv run pytest -q
